TOP=../..
include $(TOP)/configure/CONFIG

DB += types.db
DB += strings.db
DB += readback.db
DB += polling.db
DB += options.db
DB += special.db
DB += errors.db
DB += onlinechange.db

include $(TOP)/configure/RULES
